[project]
name = "sosci"
dynamic = ["version"]
description = "A package with all the important SO software and computing infrastructure."
readme = "README.md"
authors = [
    { name = "Ioannis Paraskevakos", email = "iparask@princeton.edu" }
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = []

[project.scripts]
sosci = "sosci:main"

[build-system]
requires = ["setuptools>=61", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/sosci/__about__.py"
