[project]
name = "sosci"
dynamic = ["version"]
description = "A package with all the important SO software and computing infrastructure."
readme = "README.md"
authors = [
    { name = "Ioannis Paraskevakos", email = "iparask@princeton.edu" }
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "sotodlib>=0.6.16",
    "globus_sdk>=4.0",
    "pydantic>=2.0",
    "watchdog>=3.0",
]

[project.scripts]
sosci = "sosci.__main__:main"

[build-system]
requires = ["setuptools>=61", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
sosci = ["*.txt"]

[tool.isort]
line_length = 120
profile = "black"
skip = ["docs", ".github", ".vscode", "container", "env", "env311", "build", "src/sosci/__about__.py"]

[tool.setuptools_scm]
version_file = "src/sosci/__about__.py"

[dependency-groups]
dev = [
    "black>=26.1.0",
    "isort>=7.0.0",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
    "coverage",
    "pytest-cov>=2.6",
    "coveralls>=1.5",
    "pre-commit",
]

[tool.coverage.run]
source_pkgs = ["sosci", "tests"]
branch = true
parallel = true
omit = ["src/sosci/__about__.py"]

[tool.coverage.paths]
sosci = ["src/sosci", "*/sosci/src/sosci"]
tests = ["tests", "*/sosci/tests"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover"]
exclude_also = ["if TYPE_CHECKING:"]
omit = ["*/sosci/src/sosci/__main__.py"]

[tool.ruff]
line-length = 120
exclude = ["docs", ".github", ".vscode", "container", "env", "env311", "build", "src/sosci/__about__.py"]
